name: biniou CUDA Docker Image CI

on:
  workflow_dispatch:
   
  schedule:
    - cron: '40 2 * * 6'

  push:
    branches: [ "main" ]
    paths:
      - install.sh
      - requirements.txt
      - update_cuda.sh
      - CUDA/Dockerfile
      - .github/workflows/CUDA-docker-image.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Checkout repository
      uses: actions/checkout@v6.0.2

    - name: Log in to the Container registry
      uses: docker/login-action@v4.1.0
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v6.0.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cuda
      
    - name: Build the CUDA Docker image
      run: docker build . --file CUDA/Dockerfile --tag biniou-cuda:$(date +%s)

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v7.1.0
      with:
        context: "{{defaultContext}}:CUDA"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v4.1.0
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-cuda
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

    - name: Delete outdated biniou-cuda containers
      uses: actions/delete-package-versions@main
      with:
        package-name: 'biniou-cuda'
        package-type: 'container'
        min-versions-to-keep: 5

